################################################################################
MLI_FILE		= cordova_contacts.mli
## Name which will be used in -package with ocamlfind
LIB_NAME		= cordova-plugin-contacts
################################################################################
